### ISSUE TITLE
Recursion in EVLIS has an extra A parameter

### ISSUE THREAD

**Issue by derhexenmeister** [jart/sectorlisp#12]
I was taking a close look at this file to understand the implementation, and noticed this minor typo. It doesn't seem to have an impact on the execution, but it would be nice to fix if I'm right.

Currently the recursion looks like this:
(EVLIS (CDR M) A A)

I believe that the 2nd A parameter is extraneous:
(EVLIS (CDR M) A)

Also time permitting it would be nice to elaborate on the two "NOTE:" items labeled "IS NICE" and "CAN HELP" at the top of the file. Are these checks which can be added to the first COND in EVAL? Are they not in the code because of size of performance reasons? Or because they weren't in McCarthy's paper?

**Comment by jart** [comment]
You're correct. Good catch. Want to send us a PR updating the LISP file? I've updated the website.

Those comments should probably just be deleted, since it's better left explained by a book like the one Nils Holm wrote. If you roll back history on that file and look at previous versions, I had those checks there since it makes the LISP evaluator more forgiving.

For example:

https://github.com/jart/sectorlisp/blob/8a29ec3b233492f144ff68f5bc84f0cd340fa0ae/lisp.lisp#L101

Helps differentiate undefined variable from undefined function. Previous versions of the evaluator would crash hard on undefined functions. But since it's defined as undefined behavior, it's legal to do nothing and crash. So the code was removed in the interest of tiny at the expense of all other considerations.

https://github.com/jart/sectorlisp/blob/8a29ec3b233492f144ff68f5bc84f0cd340fa0ae/lisp.lisp#L111

Having that is nice. If you add that to your evaluator then you don't need QUOTE around LAMBDA. We even received a PR for adding it in https://github.com/jart/sectorlisp/pull/8 but sadly needed to turn it down, since even though it makes for a better LISP, the aim of the project is to be tiny at the expense of all other considerations

I added the comments because having these niceties was what made it possible to develop the project in the first place. So even though they're not needed for the finished product,  I thought it might be nice to include as a suggestion for hackers who want to have fun with the codebase.

**Comment by peterferrie** [comment]
> You're correct. Good catch. Want to send us a PR updating the LISP file?
> I've updated the website.

EVLIS has left the building. :-)

**Comment by jart** [comment]
But not forgotten. Thanks again @derhexenmeister for the report.

**Comment by derhexenmeister** [comment]
And thank you so much for creating this project, and for the pointers and explanation. It looks like you handled this already. I wasn't feeling well today and took a nap :-) I've been having fun writing small programs in this environment, and may submit a PR with some example programs at a later date since it may help people understand the possibilities better.

**Comment by jart** [comment]
Please do.
